// <auto-generated />
using System;
using FleetGuard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleetGuard.Migrations
{
    [DbContext(typeof(FleetGuardDbContext))]
    [Migration("20260711211022_AddDeviceCheckInFields")]
    partial class AddDeviceCheckInFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("FleetGuard.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BatteryLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsEncrypted")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsRootedOrJailbroken")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsScreenLockEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCheckInAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystemVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Platform")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
